baseURL = 'https://alecks.dev/'
languageCode = 'en-us'
title = "Alecks 🌱"
theme="not-much"
copyright = "No copyright"
defaultContentLanguage = "en"

[languages.en.params]
  madeWith = "[Source](https://github.com/alecks20/alecks.dev)"

[params]
theme = "auto"
palette = "eink"
showThemeNotice = true
showPostsSummary = true

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 2
  
  [[menu.main]]
    identifier = "homelab"
    name = "homelab"
    title = "Homelab"
    url = "/homelab"
    weight = 3