baseURL = 'https://alecks.dev/'
languageCode = 'en-us'
title = "Alecks"
theme="hugo-bearcub"
copyright = "© Alecks 2025 "
defaultContentLanguage = "en"

[languages.en.params]
  madeWith = "[Source](https://github.com/alecks20/alecks.dev)"